### ISSUE TITLE
Dashes (-) in component names will make prettier crash

### ISSUE THREAD

**Issue by mediafreakch** [yayoc/swagger-to-flowtype#39]
```
components:
  schema:
    My-Awesome-Type:
      type: object
      properties:
        foo:
          type: string
```

```
{ SyntaxError: Unexpected token, expected "=" (2:20)
.../node_modules/swagger-to-flowtype/node_modules/prettier/parser-babylon.js:1:326
```

Even though prettier is the module crashing I think that this needs to be addressed in `swagger-to-flowtype`, because `export type My-Awesome-Type = {}` is invalid JS to begin with.

Dashes are supported in OpenAPI spec (3.0.2): https://swagger.io/docs/specification/components/

> The component names can consist of the following characters only:
> A..Z a..z 0..9 . _ -
